# Generated by Django 3.0.7 on 2021-03-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('profile', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
