# Generated by Django 3.0.7 on 2021-03-10 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210310_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
