# Generated by Django 3.0.7 on 2021-03-10 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210310_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='updated_at',
        ),
    ]
