# Generated by Django 3.0.7 on 2021-03-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_relationship_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='created_at',
        ),
    ]
