# Generated by Django 3.0.7 on 2021-03-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210312_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
